[window]
opacity = 0.9
decorations = "full"

[font]
normal = { family = "Jetbrains Mono NL Nerd Font", style = "Regular" }
size = 12.0

[colors]
[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[colors.normal]
black   = "0x282828"
red     = "0xcc241d"
green   = "0x98971a"
yellow  = "0xd79921"
blue    = "0x458588"
magenta = "0xb16286"
cyan    = "0x689d6a"
white   = "0xa89984"

[shell]
program = "/usr/bin/zsh"
